'use strict';
const questions = [
 {id:'children',kicker:'YOUR FAMILY',title:'How many children do you have?',help:'Include children you’re currently expecting.',options:['None','1','2','3','4 or more']},
 {id:'stroller_children',kicker:'YOUR EVERYDAY',title:'How many of your children currently need a stroller?',help:'Think about a typical outing, including children who use one occasionally.',options:['None','1','2','3 or more','Not yet — planning ahead']},
 {id:'current_setup',kicker:'YOUR CURRENT SETUP',title:'What do you usually use to get around with your children?',help:'Choose your most common setup.',options:['One single stroller','A tandem / inline double stroller','A side-by-side double stroller','Two separate single strollers','A stroller plus a carrier or ride-on board','No stroller / something else']},
 {id:'split_need',kicker:'YOUR REAL EXPERIENCE',title:'In the past month, how often did two caregivers need separate strollers at the same time?',help:'For example, separate errands or different plans. If this doesn’t apply, say so.',options:['Never','Once or twice','About weekly','Several times a week','Not applicable / not sure']},
 {id:'use_intent',kicker:'YOUR HONEST TAKE',title:'If this concept worked safely as described, how likely would you be to use it?',help:'Assume one tandem separates into two usable singles. We haven’t established its weight, fold size, or ease of use.',options:['Very likely','Somewhat likely','Not sure','Somewhat unlikely','Very unlikely / I wouldn’t use it']},
 {id:'use_frequency',kicker:'FITTING INTO YOUR LIFE',title:'How often would you actually separate it into two singles?',help:'Think about your current routines, rather than what might be possible.',options:['Several times a week','About weekly','Once or twice a month','Less often','Never','Not sure']},
 {id:'priorities',kicker:'WHAT MATTERS MOST',title:'What would matter most before you considered buying it?',help:'Choose up to three priorities.',multi:true,options:['Tested safety and secure connections','Low weight','Small fold / easy storage','Quick, simple separation','Easy steering in both modes','Comfort for both children','Price','Durability and repairability']},
 {id:'price_range',kicker:'THE PRACTICAL PART',title:'What total price would you consider for the complete system?',help:'In US dollars, including both seats and everything needed to use it as a tandem or two singles. This is research, not a price offer.',options:['Under $500','$500–$799','$800–$1,099','$1,100–$1,499','$1,500 or more','Not sure','I wouldn’t buy this']}
];
const $ = (selector) => document.querySelector(selector);
const answers = {}; let step = 0; let conceptSeen = false; let sending = false; let captchaToken = ''; let widgetId; let submissionId = crypto.randomUUID();
const config = window.RESEARCH_CONFIG || {};
const connected = !!(config.supabaseUrl && config.supabasePublishableKey && config.turnstileSiteKey);
function show(id,focus){ for(const name of ['landing','survey','concept','contact','thanks']) $('#'+name).hidden = name !== id; window.scrollTo({top:0,behavior:'instant'}); if(focus) $(focus).focus({preventScroll:true}); }
function render(){ const q=questions[step]; show('survey'); $('#phase-label').textContent=step<4?'01 / YOUR EVERYDAY':'03 / YOUR HONEST TAKE'; $('#step-label').textContent=`Question ${step+1} of 8`; $('#progress-fill').style.width=`${step/8*100}%`; $('.progress').setAttribute('aria-valuenow',step); $('#question-kicker').textContent=q.kicker; $('#question-title').textContent=q.title; $('#question-help').textContent=q.help; $('#side-copy').textContent=step<4?'The best place to start? Your real life.':'The idea only matters if it works for you.'; $('#question-error').textContent=''; $('#choices').replaceChildren(); for(const [i,option] of q.options.entries()){ const label=document.createElement('label'); label.className='choice'; const input=document.createElement('input'); input.type=q.multi?'checkbox':'radio'; input.name=q.id; input.value=option; input.id=`option-${i}`; input.checked=q.multi?(answers[q.id]||[]).includes(option):answers[q.id]===option; input.addEventListener('change',()=>{const selected=[...$('#choices').querySelectorAll('input:checked')]; if(q.multi&&selected.length>3){input.checked=false; $('#question-error').textContent='Choose up to three priorities.';}else $('#question-error').textContent='';}); const span=document.createElement('span');span.textContent=option;label.append(input,span);$('#choices').append(label); } $('#next').textContent=step===3?'See the concept':step===7?'Finish the questions':'Continue'; $('#question-title').focus({preventScroll:true}); }
function remember(){const q=questions[step]; const selected=[...$('#choices').querySelectorAll('input:checked')].map(x=>x.value);if(selected.length)answers[q.id]=q.multi?selected:selected[0];}
document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>{step=0;render();}));
$('#question-form').addEventListener('submit',e=>{e.preventDefault(); remember();const q=questions[step];if(!answers[q.id]||(q.multi&&!answers[q.id].length)){ $('#question-error').textContent='Please choose an answer to continue.';return;} if(step===3){conceptSeen=true;show('concept','#concept-title');}else if(step===7){show('contact','#contact-title');initCaptcha();}else{step++;render();}});
$('#back').addEventListener('click',()=>{remember(); if(step===0)show('landing');else if(step===4)show('concept','#concept-title');else{step--;render();}});
$('#concept-continue').addEventListener('click',()=>{step=4;render();});$('#concept-back').addEventListener('click',()=>{step=3;render();});$('#contact-back').addEventListener('click',()=>{step=7;render();});
$('#mode-notice').textContent=connected?'Responses are sent securely when you submit. Email is optional.':'Preview mode: explore the survey. Nothing will be sent or saved.';
async function initCaptcha(){if(!connected||widgetId!==undefined)return;if(!window.turnstile){await new Promise((resolve,reject)=>{const existing=$('#captcha-script');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.id='captcha-script';s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.onload=resolve;s.onerror=reject;document.head.append(s);}).catch(()=>{$('#submit-error').textContent='Verification could not load. Check your connection and try again.';});}if(window.turnstile){const box=document.createElement('div');box.id='captcha';$('#submit-button').before(box);widgetId=window.turnstile.render(box,{sitekey:config.turnstileSiteKey,callback:token=>{captchaToken=token;},'expired-callback':()=>{captchaToken='';},'error-callback':()=>{captchaToken='';}});}}
$('#contact-form').addEventListener('submit',async e=>{e.preventDefault();if(sending)return;$('#submit-error').textContent='';const email=$('#email').value.trim();if(email&&!$('#email-consent').checked){$('#submit-error').textContent='Please opt in to email updates, or leave the email field empty.';return;}if(!email&&$('#email-consent').checked){$('#submit-error').textContent='Enter an email address for updates, or untick the email option.';return;}if(!conceptSeen||questions.some(q=>!answers[q.id])){$('#submit-error').textContent='Please complete all eight questions first.';return;}if(!connected){show('thanks','#thanks-title');$('#thanks-copy').textContent='You’ve reached the end of the preview. No answers or email have been sent or saved. The live survey will thank respondents here after their feedback is stored.';return;}if(!captchaToken){$('#submit-error').textContent='Please complete the verification before submitting.';await initCaptcha();return;}sending=true;$('#submit-button').disabled=true;$('#submit-button').textContent='Sending your feedback…';try{const response=await fetch(`${config.supabaseUrl.replace(/\/$/,'')}/functions/v1/submit-research`,{method:'POST',headers:{'Content-Type':'application/json','apikey':config.supabasePublishableKey},body:JSON.stringify({submission_id:submissionId,answers,email:email||null,email_consent:!!email&&$('#email-consent').checked,research_consent:$('#research-consent').checked,consent_version:'2026-10-02',survey_version:'1',currency:'USD',website:$('#website').value,captcha_token:captchaToken}),signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error('Submission failed');show('thanks','#thanks-title');$('#thanks-copy').textContent=email?'Your feedback has been saved. You’re also on the list for concept updates and future research invitations.':'Your feedback has been saved. Thanks for helping us understand what families actually need.';}catch{$('#submit-error').textContent='Your feedback could not be saved. Your answers are still here. Please check your connection and try again.';captchaToken='';if(window.turnstile&&widgetId!==undefined)window.turnstile.reset(widgetId);}finally{sending=false;$('#submit-button').disabled=false;$('#submit-button').textContent='Submit my feedback';}});
document.querySelectorAll('[data-privacy]').forEach(b=>b.addEventListener('click',()=>$('#privacy').showModal()));for(const id of ['close-privacy','privacy-done'])$('#'+id).addEventListener('click',()=>$('#privacy').close());
$('#restart').addEventListener('click',()=>{for(const key of Object.keys(answers))delete answers[key];step=0;conceptSeen=false;submissionId=crypto.randomUUID();$('#contact-form').reset();captchaToken='';if(window.turnstile&&widgetId!==undefined)window.turnstile.reset(widgetId);show('landing');});
